### ISSUE TITLE
NPE in 2.2.9

### ISSUE THREAD

**Issue by frapontillo** [frakbot/FWeather#112]
And then hell broke loose.
As of 2.2.9 we are receiving plenty of NPEs:

```
java.lang.NullPointerException
at android.widget.RemoteViews$SetOnClickPendingIntent.writeToParcel(RemoteViews.java:147)
at android.widget.RemoteViews.writeToParcel(RemoteViews.java:1376)
at com.android.internal.appwidget.IAppWidgetService$Stub$Proxy.updateAppWidgetIds(IAppWidgetService.java:374)
at android.appwidget.AppWidgetManager.updateAppWidget(AppWidgetManager.java:246)
at android.appwidget.AppWidgetManager.updateAppWidget(AppWidgetManager.java:265)
at net.frakbot.FWeather.updater.UpdaterService.onHandleIntent(UpdaterService.java:164)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:59)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:130)
at android.os.HandlerThread.run(HandlerThread.java:60)
```

The affected devices are (wait for it... wait for it...) Samsung:
- Galaxy Y (GT-S5360B)
- Galaxy Ace (GT-S5830i)
- GT-I5510T (GT-I5510T)
- Galaxy Ace (GT-S5839i)
- Galaxy S2 (GT-I9100)
- Galaxy Y TV (GT-S5367)
- Galaxy Y Pro (GT-B5510)
- Galaxy Mini (GT-S5570)
- Galaxy Ace (GT-S5830B)
- Galaxy Y (GT-S5363)
- Galaxy Ace (GT-S5830C)
- Galaxy Y (GT-S5360)
- SGH-S959G (SGH-S959G)

We have also received 1-star feedbacks (...) and several emails of people who complained the widget always crashes.

**Comment by frapontillo** [comment]
The problem has started occuring since 2.2.4, that is since the introduction of the sharing function.
It should be related to some `PendingIntent` being `null` or somehow invalid.

See http://stackoverflow.com/questions/6060181/android-widget-null-pointer-exception-when-using-setonclickpendingintent-on and http://www.blogosfera.co.uk/2013/09/unable-to-start-receiver-crash-for-widgets-on-android-4-0-4-device/.

**UPDATE:**
This is the same issue as #105, that wasn't solved by 20468927e0bd1fedd8bc7905e709381ce63a18bc. Besides the refresh PendingIntent, there is the ["share" `PendingIntent`](https://github.com/frakbot/FWeather/blob/develop/src/net/frakbot/FWeather/updater/UpdaterService.java#L381) as well. 

Since it looks like there's no way to avoid the bug, we can either opt to:
- disregard the fact that there is no new data (or no data at all, for first start) and not set the `PendingIntent`, just like you did in 20468927e0bd1fedd8bc7905e709381ce63a18bc
- always go through the weather string generation, even with no data; this way the share function will give some error text, the same displayed by the widget

This needs to be fixed ASAP.

**Comment by rock3r** [comment]
I'd probably just hide the share button when we don't have data. Simple and makes perfect sense.

**Comment by frapontillo** [comment]
That'd be a valid option as well.

**Comment by rock3r** [comment]
Then go for it :)
