### ISSUE TITLE
IllegalArgumentException in Play Services

### ISSUE THREAD

**Issue by rock3r** [frakbot/FWeather#79]
Reported by some users.
Looks like the app passes a negative update interval to the Fused Location.

```
java.lang.IllegalArgumentException: invalid interval: -1000
at com.google.android.gms.location.LocationRequest.c(Unknown Source)
at com.google.android.gms.location.LocationRequest.setFastestInterval(Unknown Source)
at net.frakbot.FWeather.util.LocationHelper$LocationClientListener.onConnected(LocationHelper.java:247)
at com.google.android.gms.internal.k.y(Unknown Source)
at com.google.android.gms.internal.k$f.a(Unknown Source)
at com.google.android.gms.internal.k$f.a(Unknown Source)
at com.google.android.gms.internal.k$b.D(Unknown Source)
at com.google.android.gms.internal.k$a.handleMessage(Unknown Source)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5103)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:525)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
at dalvik.system.NativeStart.main(Native Method)
```

**Comment by rock3r** [comment]
Should be fixed as of 5719bcb
