### ISSUE TITLE
Weird error on update rate

### ISSUE THREAD

**Issue by frapontillo** [frakbot/FWeather#97]
A user reported a crash on every update. It looks like his SharedPreferences were pretty effed up, as it was trying to set an update for `-1000` seconds. Yeah.

```
11-28 13:50:00.171  3317  3345 I FWeather-v18-WeatherHelper: Starting weather update
11-28 13:50:00.196  3317  3317 D AndroidRuntime: Shutting down VM
11-28 13:50:00.196  3317  3317 W dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x41a457c0)
11-28 13:50:00.196  3317  3317 E AndroidRuntime: FATAL EXCEPTION: main
11-28 13:50:00.196  3317  3317 E AndroidRuntime: java.lang.IllegalArgumentException: invalid interval: -1000
11-28 13:50:00.196  3317  3317 E AndroidRuntime: at com.google.android.gms.location.LocationRequest.c(Unknown Source)
11-28 13:50:00.196  3317  3317 E AndroidRuntime: at com.google.android.gms.location.LocationRequest.setFastestInterval(Unknown Source)
11-28 13:50:00.196  3317  3317 E AndroidRuntime: at net.frakbot.FWeather.util.LocationHelper$LocationClientListener.onConnected(LocationHelper.java:247)
11-28 13:50:00.196  3317  3317 E AndroidRuntime: at com.google.android.gms.internal.k.y(Unknown Source)
11-28 13:50:00.196  3317  3317 E AndroidRuntime: at com.google.android.gms.internal.k$f.a(Unknown Source)
11-28 13:50:00.196  3317  3317 E AndroidRuntime: at com.google.android.gms.internal.k$f.a(Unknown Source)
11-28 13:50:00.196  3317  3317 E AndroidRuntime: at com.google.android.gms.internal.k$b.D(Unknown Source)
11-28 13:50:00.196  3317  3317 E AndroidRuntime: at com.google.android.gms.internal.k$a.handleMessage(Unknown Source)
11-28 13:50:00.196  3317  3317 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:99)
11-28 13:50:00.196  3317  3317 E AndroidRuntime: at android.os.Looper.loop(Looper.java:137)
11-28 13:50:00.196  3317  3317 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:5295)
11-28 13:50:00.196  3317  3317 E AndroidRuntime: at java.lang.reflect.Method.invokeNative(Native Method)
11-28 13:50:00.196  3317  3317 E AndroidRuntime: at java.lang.reflect.Method.invoke(Method.java:525)
11-28 13:50:00.196  3317  3317 E AndroidRuntime: at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
11-28 13:50:00.196  3317  3317 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:555)
11-28 13:50:00.196  3317  3317 E AndroidRuntime: at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:126)
11-28 13:50:00.196  3317  3317 E AndroidRuntime: at dalvik.system.NativeStart.main(Native Method)
11-28 13:50:01.011  3317  3345 I FWeather-v18-WeatherHelper: Weather update done
11-28 13:50:01.026  3317  3345 I FWeather-v18-UpdaterService: Updating the widget views for widget #4
11-28 13:50:01.056  3317  3345 I FWeather-v18-UpdaterService: All widgets updated successfully
```

**Comment by frapontillo** [comment]
Already fixed, me tired.
